encoding: utf-8

# site meta
title: Quedic
description: Shaping the Future of Money through Influential Financial and Cryptocurrency Insights
keywords: 关键词1,关键词2

# build config
baseurl: ''
permalink: /post/:name.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'run.sh']

# sass config
sass:
  sass_dir: _sass
  style: compressed

language:
  - lang: es
    img: https://cdn.countryflags.com/thumbs/spain/flag-400.png
    text: Spanish

  - lang: fr
    img: https://cdn.countryflags.com/thumbs/france/flag-400.png
    text: French

  - lang: zh-TW
    img: https://cdn.countryflags.com/thumbs/hongkong/flag-400.png
    text: Chinese(Simple)

  - lang: ja
    img: https://cdn.countryflags.com/thumbs/japan/flag-400.png
    text: Japanese

  - lang: ru
    img: https://cdn.countryflags.com/thumbs/russia/flag-400.png
    text: Russian

  - lang: en
    img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
    text: English



author:
  - name: Meltem Demiror
    head: /assets/img/partners-01.jpg

  - name:  Dovey Wan
    head: /assets/img/partners-02.jpg

  - name: Metaverse Princess （元宇宙公主）
    head: /assets/img/partners-03.jpg

  - name: Rocio Han
    head: /assets/img/partners-04.jpg

  - name: BINANCE
    head: /assets/img/partners-05.jpg

  - name: MarketAcross
    head: /assets/img/partners-06.jpg

