keywords: 关键词1,关键词2

# build config
baseurl: '' # the subpath of your site, e.g. /blog
url: "https://www.quedicshares.com" # the base hostname & protocol for your site
repository: thatbrianlau/thatbrianlau.github.io # Add repository name here
permalink: /post/:name.html
kramdown:
  auto_ids: true
sass:
  sass_dir: _sass
  style: compressed

# multilingual config
language:
  - lang: es
    img: https://cdn.countryflags.com/thumbs/spain/flag-400.png
  - lang: en
    img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
    text: English

# authors config
author:
  - name: Meltem Demiror
    head: /assets/img/partners-01.jpg
  - name: Dovey Wan
    head: /assets/img/partners-02.jpg
  - name: Metaverse Princess （元宇宙公主）
    head: /assets/img/partners-03.jpg
  - name: Quedic
    head: /assets/img/partners-21.jpg

# other settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
paginate: 12
paginate_path: "/latest/page/:num"
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /latest/:slug
  authors:
    output: true
    permalink: /:name
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: "tag"
      type: "pages"
    values:
      layout: "tag"
sass:
  sass_dir: _sass
  style: compressed

# tag settings
tag_page_layout: tag
tag_page_dir: tag
