keywords: 关键词1,关键词2

# build config
baseurl: ''
permalink: /post/:name.html
kramdown:
  auto_ids: true
	@@ -19,6 +20,7 @@ sass:
  sass_dir: _sass
  style: compressed

language:
  - lang: es
    img: https://cdn.countryflags.com/thumbs/spain/flag-400.png
	@@ -48,13 +50,12 @@ language:
    img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
    text: English



author:
  - name: Meltem Demiror
    head: /assets/img/partners-01.jpg

  - name:  Dovey Wan
    head: /assets/img/partners-02.jpg

  - name: Metaverse Princess （元宇宙公主）
	@@ -66,4 +67,52 @@ author:
  - name: Quedic
    head: /assets/img/partners-21.jpg

