encoding: utf-8

# site meta
title: Quedic
description: The Beacon of Financial Insight, Guiding the Future of Cryptocurrency
keywords: 关键词1,关键词2

# build config
baseurl: ''
permalink: /post/:name.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'run.sh']

# sass config
sass:
  sass_dir: _sass
  style: compressed

language:
  - lang: es
    img: https://cdn.countryflags.com/thumbs/spain/flag-400.png
    text: Spanish

  - lang: fr
    img: https://cdn.countryflags.com/thumbs/france/flag-400.png
    text: French

  - lang: zh-TW
    img: https://cdn.countryflags.com/thumbs/hongkong/flag-400.png
    text: Chinese(Simple)

  - lang: ja
    img: https://cdn.countryflags.com/thumbs/japan/flag-400.png
    text: Japanese

  - lang: ru
    img: https://cdn.countryflags.com/thumbs/russia/flag-400.png
    text: Russian

  - lang: en
    img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
    text: English

author:
  - name: Alena Curtis
    head: /assets/img/partners-01.jpg
    introduction: I have experience in photographing beauty, fashion, e-commerce, and product photography for various brands.

  - name: Nolan Bergson
    head: /assets/img/partners-02.jpg
    introduction: I can and will deliver great results with a process that’s timely, collaborative and at a great value for my clients.

  - name: Tiana Dorwart
    head: /assets/img/partners-03.jpg
    introduction: Hi, my name is Tiana, I'm originally from Finland, but I have been living in Spain for almost three years now.
