encoding: utf-8

# site meta
title: Quedic
description: The Beacon of Financial Insight, Guiding the Future of Cryptocurrency
keywords: 关键词1,关键词2

# build config
baseurl: ''
permalink: /post/:name.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'run.sh']

# sass config
sass:
  sass_dir: _sass
  style: compressed

language:
  - lang: es
    img: https://cdn.countryflags.com/thumbs/spain/flag-400.png
    text: Spanish

  - lang: fr
    img: https://cdn.countryflags.com/thumbs/france/flag-400.png
    text: French

  - lang: zh-TW
    img: https://cdn.countryflags.com/thumbs/hongkong/flag-400.png
    text: Chinese(Simple)

  - lang: ja
    img: https://cdn.countryflags.com/thumbs/japan/flag-400.png
    text: Japanese

  - lang: ru
    img: https://cdn.countryflags.com/thumbs/russia/flag-400.png
    text: Russian

  - lang: en
    img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
    text: English

author:
  - name: Meltem Demiror
    head: /assets/img/partners-01.jpg
    introduction: >
      Meltem Demirors is Chief Strategy Officer of CoinShares, a digital asset investment firm that manages $4B in assets on behalf of a global client base, and serves as a trusted partner to investors and entrepreneurs navigating the digital asset ecosystem.
      
      An established veteran of digital asset investing, Meltem draws on her substantial experience and widespread influence to accelerate growth and acceptance of the asset class. Prior to joining CoinShares, Meltem helped build and grow Digital Currency Group, raising capital from the world’s largest corporations and managing a portfolio of 120 companies and 4 subsidiaries. Before she was bitten by the bitcoin bug, Meltem worked in the Oil & Gas industry in trading, corporate treasury, and M&A roles.
      
      Meltem has been recognized for her personal contributions to the industry and serves as an outspoken advocate. She is a founding member and co-chair of the World Economic Forum Cryptocurrency Council and testified before the House Financial Services Committee on the importance of bitcoin.
      
      Meltem teaches at her alma mater MIT as well as Oxford, and is passionate about privacy and civil rights.

  - name:  Dovey Wan
    head: /assets/img/partners-02.jpg
    introduction: Dovey Wan is Founding Partner of Primitive Ventures, a long-term focused cryptoasset investment fund she founded with Eric Meltzer. Prior to founding Primitive Ventures, Dovey served as Managing Director for DHVC (formerly Danhua Capital), where she participated in investments in marquee blockchain projects such as OmiseGo, Cosmos/Tendermint, and Kyber Network. Outside of blockchain ventures she also participated in investments in LimeBike, LoomAi, Chariot, and Flexport. She began her career at eBay, where she spent nearly 4 years progressing through Data Science Engineer, Senior Business Analyst, and Product Manager roles.

  - name: Metaverse Princess （元宇宙公主）
    head: /assets/img/partners-03.jpg
    introduction: NFT Creator Economy | Founder of Metaverse Guide, author of the book 《Web3.0漫遊指南》"Web3.0 Roaming Guide”
