name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install Bundler
      run: gem install bundler

    - name: Install dependencies
      run: |
        bundle install || true

    - name: Check bundle configuration
      run: bundle config

    - name: Remove invalid post template
      run: |
        rm -f vendor/bundle/ruby/3.1.0/gems/jekyll-3.9.3/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb

    - name: Generate Gemfile.lock if not exists
      run: |
        if [ ! -f Gemfile.lock ]; then
          bundle lock
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add Gemfile.lock
          git commit -m 'Generate Gemfile.lock'
          git push origin main
        fi

    - name: Build Jekyll site
      run: bundle exec jekyll build --trace

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
